# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_crtdt', models.DateTimeField(auto_now_add=True)),
                ('todo_detail', models.CharField(max_length=100)),
                ('todo_duedt', models.DateTimeField()),
                ('todo_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
